# Generated by Django 5.1.4 on 2025-01-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='city',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='first_name',
            new_name='nation',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='address',
            new_name='vision',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='last_name',
            new_name='weapon',
        ),
        migrations.RemoveField(
            model_name='record',
            name='email',
        ),
        migrations.RemoveField(
            model_name='record',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='record',
            name='state',
        ),
        migrations.RemoveField(
            model_name='record',
            name='zipcode',
        ),
    ]
